#! /bin/bash

# Helper script to call the Payara Utility Tool
#
# Author: Matt Gill

SCRIPT_DIR=$(dirname $(readlink -f $0))

java -cp "${SCRIPT_DIR}/target/classes:${SCRIPT_DIR}/target/lib/*" uk.me.mattgill.payara.tools.Main "$@"